# Generated by Django 5.0.7 on 2024-08-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Post_Title', models.CharField(max_length=200)),
                ('Post_Desc', models.TextField()),
                ('Post_photo', models.ImageField(upload_to='posts/')),
                ('Auther', models.CharField(max_length=100)),
                ('Post_Date', models.DateField(auto_now=True)),
            ],
        ),
    ]
